"""Import all model modules so Alembic can discover complete metadata."""

from app.db.models.chat import (
    AgentRun,
    AgentRunMemory,
    AgentToolCall,
    Conversation,
    Message,
    MessageEvidence,
)
from app.db.models.finance import (
    Budget,
    ExchangeRateSnapshot,
    FinancialAccount,
    FinancialTransaction,
    InvestmentHolding,
    InvestmentTransaction,
    MarketPriceSnapshot,
)
from app.db.models.identity import (
    AuditLog,
    EmploymentStatus,
    MemoryCategory,
    MemoryConfirmationStatus,
    MemoryEmbeddingStatus,
    MemorySourceType,
    MemoryStatus,
    PersonalFinancialProfile,
    RefreshToken,
    User,
    UserMemory,
    UserMemoryConfirmation,
    UserMemorySettings,
    UserPreference,
    UserProfile,
)

__all__ = [
    "AgentRun",
    "AgentRunMemory",
    "AgentToolCall",
    "AuditLog",
    "Budget",
    "Conversation",
    "ExchangeRateSnapshot",
    "EmploymentStatus",
    "FinancialAccount",
    "FinancialTransaction",
    "InvestmentHolding",
    "InvestmentTransaction",
    "MarketPriceSnapshot",
    "MemoryCategory",
    "MemoryConfirmationStatus",
    "MemoryEmbeddingStatus",
    "MemorySourceType",
    "MemoryStatus",
    "Message",
    "MessageEvidence",
    "PersonalFinancialProfile",
    "RefreshToken",
    "User",
    "UserMemory",
    "UserMemoryConfirmation",
    "UserMemorySettings",
    "UserPreference",
    "UserProfile",
]
