"""Shared invariants for the initial knowledge-ingestion pipeline."""

DASHSCOPE_EMBEDDING_PROVIDER = "dashscope"
DASHSCOPE_TEXT_EMBEDDING_V4 = "text-embedding-v4"
DASHSCOPE_TEXT_EMBEDDING_V4_DIMENSIONS = 1024
DASHSCOPE_QWEN3_RERANK = "qwen3-rerank"
DASHSCOPE_RERANK_BASE_URL = "https://dashscope.aliyuncs.com/compatible-api/v1"
COSINE_DISTANCE_METRIC = "cosine"

DOCUMENT_STATUS_UPLOADED = "uploaded"
DOCUMENT_STATUS_PUBLISHED = "published"
DOCUMENT_STATUS_DISABLED = "disabled"
DOCUMENT_STATUS_DELETED = "deleted"
DOCUMENT_VERSION_STATUS_UPLOADING = "uploading"
DOCUMENT_VERSION_STATUS_AWAITING_PIPELINE = "awaiting_pipeline"
DOCUMENT_VERSION_STATUS_PROCESSING = "processing"
DOCUMENT_VERSION_STATUS_PUBLISHED = "published"
DOCUMENT_VERSION_STATUS_SUPERSEDED = "superseded"
DOCUMENT_VERSION_STATUS_FAILED = "failed"
INGESTION_JOB_STATUS_AWAITING_PIPELINE = "awaiting_pipeline"
INGESTION_JOB_STATUS_PROCESSING = "processing"
INGESTION_JOB_STATUS_COMPLETED = "completed"
INGESTION_JOB_STATUS_FAILED = "failed"
OUTBOX_EVENT_INGESTION_REQUESTED = "rag.ingestion.requested"
OUTBOX_STATUS_PENDING = "pending"
OUTBOX_STATUS_PUBLISHED = "published"
OUTBOX_STATUS_FAILED = "failed"
OUTBOX_DEFAULT_MAX_ATTEMPTS = 8
UPLOAD_REQUEST_TARGET_KNOWLEDGE_BASE = "knowledge_base"
UPLOAD_REQUEST_TARGET_DOCUMENT = "document"
UPLOAD_REQUEST_STATUS_RESERVED = "reserved"
UPLOAD_REQUEST_STATUS_STORED = "stored"
UPLOAD_REQUEST_STATUS_ACTIVATED = "activated"
UPLOAD_REQUEST_STATUS_FAILED = "failed"

MAX_DOCUMENT_FILENAME_LENGTH = 512
MAX_DOCUMENT_METADATA_ENTRIES = 16
MAX_DOCUMENT_METADATA_KEY_LENGTH = 64
MAX_DOCUMENT_METADATA_VALUE_LENGTH = 512
